spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: we-chat
  redis:
    database: 0
    host: 120.79.46.56
    port: 6379
    timeout: 1000
    password: 5vwJ4AghYNH&W4RWejfieo69C2ZPp%r@
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0

server:
  #20400~20500
  port: 20400
  tomcat:
    max-swallow-size: -1
  error:
    include-exception: true
    include-stacktrace: ALWAYS
    include-message: ALWAYS
  servlet:
    context-path: /${spring.application.name}
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*


wx:
  the-public:
    appId: wx79a80d8e2a8b3376
    appSecret: d5c0e2d832f4279e39704538214451a6
